### PR TITLE
Addresses #9. Adds and encapsulates logic for determining whether a PriceField should be considered active.

### PR DESCRIPTION
**Pull request by universalhandle**

### CODE REVIEW

**Comment by universalhandle** [comment]
@ginkgomzd: See discussion on #9.

**Review by caracolmzd — COMMENTED** [review]
sorry for being pedantic...

Your comments are explaining what you are doing, not why... so they will someday become out of date and misleading. 

I do favour bailing out of functions early when possible, as you do, which is an exception to my next complaint.

Functions should not have multiple return points. Since this is a boolean function, why not keep it short and sweet? Here is how I would do it...

    $now = time();
    $expireTime = strtotime(CRM_Utils_Array::value('expire_on', $field));
    $activeTime = strtotime(CRM_Utils_Array::value('active_on', $field));

    return ( 
        ($expireTime === FALSE || $now < $expireTime )
        && ($activeTime === FALSE || $activeTime < $now )
    );

**Comment by universalhandle** [comment]
I generally don't like functions with multiple returns either, but there is a class of function for which I make an exception. It's a little hard to articulate, but I'll give it a try: If the return value is boolean, and there's a default return value at the bottom of the function, and the logic in the function only serves to bail out from that default, then it's okay by me.

Your proposed code is more compact for sure, but I find it harder to follow. I feel like I have to hold more in my head to predict what the outcome will be.

I find my approach to be more scalable. If another factor is introduced (e.g., only consider the field to be active if its options list is not empty), then your compound expression becomes even more complex. My code becomes longer, but no less difficult to walk through.

I'll agree that my comment is not as accurate as it could be: "Check if inactive only if the time string is parseable" is better than "Consider the pricefield active if the time string is not parseable." I'll update that if you come around to my way of thinking on the other questions -- otherwise, it's moot.

**Comment by caracolmzd** [comment]
mmm I can see the point about scalability with a large boolean expression... but I don't agree that it is less readable.
It clearly reads to me, "If there is no expiration set or the expiration is not passed, and there is no start date or it is already passed".

Someone could come in and add logic and totally trash the readability, but they could also maintain the readability by setting a boolean variable. e.g.

$permissionVerified = ( userHasPermission() && notFriday13th());

...

return ( 
    ($expireTime === FALSE || $now < $expireTime )
    && ($activeTime === FALSE || $activeTime < $now )
    && ($permissionVerified)
);

I think one of the textbook arguments against multiple function returns is maintainability and a type of scalability (increasing logic). If code is getting added, and the returns get further and further apart, it can be easy to miss a return earlier in the function when you are working later in the function.

I think that I'm still on the side of a single return statement and if you don't like the logic, then pre-test to make the final test more readable:

return (
    $notExpired && $hasStarted
);

**Comment by universalhandle** [comment]
Okay, well I decided to go all in and give it only one return. Shall we call it done?

**Pull request merged**
